### ISSUE TITLE
--Azure flag doesn't work

### ISSUE THREAD

**Issue by HackAndPwn** [Mazars-Tech/AD_Miner#12]
When using the --Azure flag I am getting an error that I don't get if I skip that flag.  Looks to me like perhaps lines 67-1169 (in neo4j_class.py) need to have an extra tab removed?  I manually untabbed those lines and then rebuilt the package and it no longer errors out when using that flag, but if you cannot reproduce I can get the exact error message.  Thanks!

**Comment by jmbesnard** [comment]
Thanks a lot for pointing this out. Feel free to create a PR (or we will fix it next time we commit something).
The --azure will add a few AZ-specific edges but the list of edges is not necessarily up-to-date with latest additions.
AZ support is something that we need to work on.

**Comment by HackAndPwn** [comment]
This doesn't appear fixed yet  Get the following error when using the --azure flag

```
AttributeError: 'Neo4j' object has no attribute 'all_requests'
```

**Comment by jmbesnard** [comment]
We will look into it but, again, do not expect much from this option as it only adds a bunch of edges and Azure it something that we really need to work on.
