### ISSUE TITLE
Issue running AD miner 

### ISSUE THREAD

**Issue by suriya73** [Mazars-Tech/AD_Miner#148]
**Describe the bug**
Running AD miner with the log collected with SharpHound throws error "empty neo4j database"

**Terminal Output**
`[!]Empty neo4j database : you need to collect data with Sharphound (https://github.com/BloodHoundAD/SharpHound), BloodHound.py (https://github.com/dirkjanm/BloodHound.py) or RustHound (https://github.com/NH-RED-TEAM/RustHound)                                                                        
[!]And then you can fill your neo4j database with Bloodhound (https://github.com/BloodHoundAD/BloodHound)
`

**Screenshots**
<img width="601" alt="image" src="https://github.com/Mazars-Tech/AD_Miner/assets/5960769/106ec118-14de-4959-bbe0-aec5b2f00073">

**System information**
 - Linux kali 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux
 - Python 3.11.4

**Comment by jmbesnard** [comment]
Thanks for reporting this.

This error message was created especially for cases likes yours :)

Basically, as described in the documentation, AD-Miner needs to connect to a database that has previously been populated with data (i.e., just like when you use Bloodhound)
