### ISSUE TITLE
AD Miner install in Windows 10 via pipx drops error (Python 3.12.0)

### ISSUE THREAD

**Issue by jd3141** [Mazars-Tech/AD_Miner#15]
I just ran it from cmdline as shown in README and got this error: "_module 'pkgutil' has no attribute 'ImpImporter'_". Please help if possible.

```
pipx install 'git+https://github.com/Mazars-Tech/AD_Miner.git'
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\user\.local\pipx\logs\cmd_2023-10-03_12.07.56_pip_errors.log

pip seemed to fail to build package:
    neo4j==5.6.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Error installing AD_Miner from spec 'git+https://github.com/Mazars-Tech/AD_Miner.git'.
```

**Comment by jd3141** [comment]
This pip version (23.2.1) was installed as a part of the installation of Python 3.12.0

**Comment by jmbesnard** [comment]
A little investigation seems to conclude that the issues comes, not from AD Miner, not even from neo4j but from python 3.12.0. Version 3.11.0 does not show dependencies issues so you might find a temporary solution in downgrading to 3.11.0

**Comment by jd3141** [comment]
ok, thanks for looking into it.
