### ISSUE TITLE
compromise_path_of_OUs and vulnerable_OU_impact missing from config.json

### ISSUE THREAD

**Issue by robwillisinfo** [Mazars-Tech/AD_Miner#166]
The following options appear missing from the current version of the default config.json:
compromise_path_of_OUs
vulnerable_OU_impact

Adding them manually allowed the options to be disabled.

With these options enabled AD-miner would hang indefinitely at "Computing domains objects", once disabled along with the KUD one, everything works as expected.

**Comment by jmbesnard** [comment]
fixed
