### ISSUE TITLE
Script stuck at "Non-Domain Admin that can directly or indirectly impersonate a Domain Controller"

### ISSUE THREAD

**Issue by WovenAxil** [Mazars-Tech/AD_Miner#177]
**Describe the bug**
After executing the scripts(retried with multiple attempts) & upgrading to the latest version 1.6.0
The script will still be stuck at "Non-Domain Admin that can directly or indirectly impersonate a Domain Controller" indefinitely without any progress.

But after setting the "dc_impersonation" in the config.json to "**false**", the script will be able to continue to work.

**Terminal Output**
N/A

**Screenshots**
Prior setting the "dc_impersonation" in the config.json to "**false**"
![AD_Miner Script runtime stuck](https://github.com/user-attachments/assets/17352f25-d85c-4eb8-9fa7-38ac0a55b1b2)

After setting the "dc_impersonation" in the config.json to "**false**"
![Disabling dc_impersonation](https://github.com/user-attachments/assets/58cdbbe4-cc55-4020-a25c-8e59c11f0b35)

**System information**
 - OS : Red Hat Enterprise Linux 8.10
 - Python version  : 3.9.16

**Additional context**
N/A

**Comment by leJoPra** [comment]
Hi, it looks like you are handling a huge AD. 
You can try replacing actual "dc_impersonation" request with this. It will enable multi threading and should speed up the process. You can find the request in sources/modules/requests.json :
    "dc_impersonation": {
        "name": "Non-domain admins that can directly or indirectly impersonate a Domain Controller ",
        "request": "MATCH (u{ou_candidate:true}) WITH u ORDER BY u.name SKIP PARAM1 LIMIT PARAM2 CALL{MATCH p=(u)-[r:MemberOf*1..5]->(g:Group)-[r3:AddKeyCredentialLink|WriteProperty|GenericAll|GenericWrite|Owns|WriteDacl]->(m:Computer{is_dc:true}) RETURN p UNION ALL MATCH p=(u)-[r3:AddKeyCredentialLink|WriteProperty|GenericAll|GenericWrite|Owns|WriteDacl]->(m:Computer{is_dc:true}) RETURN p }RETURN DISTINCT p
",
	"scope_query":"MATCH (u{ou_candidate:true}) RETURN count(u)",
        "output_type": "Graph"
}



Next release will include this change.

**Comment by WovenAxil** [comment]
Hi @leJoPra ,

Thanks for the reply. I will give it a test first it may take some time.

But I encountered what it seems to be another issue currently.

I had left the script to run and monitor if the report can generated. But it seems like it is stuck at "Computing Domain Object" for at least 1 day. Is there any solution I could try to fix this?
![image](https://github.com/user-attachments/assets/bdb19de9-92b9-4ace-ba56-895c28602f79)

**Comment by leJoPra** [comment]
Hi, 
As your dataset ie very large, Python computing will take a (very) long time to finish. We might add a new feature to appreciate the progress for each step in the last part. 
As for now, I would recommend to let it run longer and hope that this will not take too many days.

**Comment by WovenAxil** [comment]
Hi @leJoPra ,

Thank you for the update.
I will give it more time to generate on the next execution. 
As for the current previous info provided for the "dc_impersonation" request. I had updated the it and it is working now.
![image](https://github.com/user-attachments/assets/d15fe081-4149-435e-8cfd-ea9eda515d94)


Thank you for the assistance.
