### ISSUE TITLE
Slow processing of the path generation function for RBCD on computers

### ISSUE THREAD

**Issue by TourioN** [Mazars-Tech/AD_Miner#188]
Hello! I really like your project, but is it possible to parallelize the load between cores at all stages of report creation? Because now only 1 processor core is used when generating RBCD paths.
Thanks in advance

**Comment by snowpeacock** [comment]
Hello,

Unfortunately, this is not possible at the moment. However we are working on a new version that fixes a lot of (big) performance issues. 

It should also be more verbose, so we will be able to take a closer look if your problem persists after the next release.

**Comment by jmbesnard** [comment]
Hi. I believe that are mixing different issues that are somehow unrelated.
You problem with #192 is that your neo4j DB is running out of memory.

Also, could you make sure that you are using the latest version of AD Miner (released yesterday).

thanks
