### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

### ISSUE THREAD

**Issue by obiwan420** [Mazars-Tech/AD_Miner#194]
Received this error when running AD-Miner v1.7 for the first time

![image](https://github.com/user-attachments/assets/623867b3-a972-467f-8c49-1e07aae618e0)
                                                                   
**System information**
 - OS Kali 2024.4
 - Python v3.12.6

**Comment by obiwan420** [comment]
I ran it a second time and got the same error, but this time I notice that it appears the AD-miner if finished gathering data and building the report when it loops back to the beginning?!? 
![image](https://github.com/user-attachments/assets/a6195e0c-ce55-4331-afaf-85bc48dcfe49)

**Comment by snowpeacock** [comment]
Hello, I guess you use the evolution flag ? How many json are you using ?

About the second screen, it's not looping back, it's just that we added logs for the python control generation as well.

**Comment by obiwan420** [comment]
Ok that makes sense. I do have about 6 months' worth of evolution json files.

**Comment by snowpeacock** [comment]
Ok.

By any change have you tried modifying them manually before running AD Miner (to adjust numbers, ...) ?

**Comment by obiwan420** [comment]
That will be my next test.

**Comment by obiwan420** [comment]
No error when not using the evolution switch. Going to run it again with about a weeks of jsons and see what happens.

**Comment by obiwan420** [comment]
Errored out when using evolution. I only had 5 json files in the evolution folder

**Comment by obiwan420** [comment]
I ran AD Miner with just one json for evolution and it errored out the same.

**Comment by snowpeacock** [comment]
For those who might want the fix before the release:

find the file graph_path_objects_to_ou_handlers.py (maybe in your pipx folder, something like modules/controls/graph_path_objects_to_ou_handlers.py)

at the end of the file change this:

        self.data = (
            (len(self.compromise_paths_of_OUs) if self.compromise_paths_of_OUs else 0),
        )


 to this:

`self.data = len(self.compromise_paths_of_OUs) if self.compromise_paths_of_OUs else 0`

**Comment by obiwan420** [comment]
I just tested the code above and it worked without the mention error reported in this issue. However, no evolution data was included in the report when using the evolution switch.

**Comment by obiwan420** [comment]
Looking at the report, it appears all the evolution data was included but is not being displayed. My oldest evolution json is from March 1st 2024. In the AD Miner report under evolution I can see the chart dates back to March 1st 2024 but there is no data in the chart, all categories show zero issues for every data.

**Comment by snowpeacock** [comment]
Hello,
The histogram view is indeed buggy (and will hopefully be fixed by https://github.com/Mazars-Tech/AD_Miner/commit/f9db36caf28749db89505f89351dab4ed1bac3f9).
However, you should see evolution graphs for controls (when you click on "permissions", "kerberos", etc. on the main page and then on the evolution button).

**Comment by snowpeacock** [comment]
Hello,
This should be fixed in the new version we just released (1.8.0).
Don't forget to update (pipx upgrade AD-miner).
