### ISSUE TITLE
Python\Python310\lib\runpy.py", line 196, in _run_module_as_main

### ISSUE THREAD

**Issue by hanysoliman2020** [Mazars-Tech/AD_Miner#20]
i got this error 
kindly support 
![image](https://github.com/Mazars-Tech/AD_Miner/assets/33179356/593eee2d-e70c-4543-9dbe-5cde09ca75c6)

**Comment by jmbesnard** [comment]
Until the fix for GPO names containing special chars (in particular "/" in your case), I suggest to disable GPO checks in config.json (set them to false). Also make sure that you delete already cached cypher queries result (rm all file with *GPO* in folder cache_neo4j).
