### ISSUE TITLE
Multiple errors in version 1.8.0

### ISSUE THREAD

**Issue by obiwan420** [Mazars-Tech/AD_Miner#208]
Tested the new version of AD Miner. Below are the error messages that where produced.

**Terminal Output**
![image](https://github.com/user-attachments/assets/65b389c5-f361-456c-8c87-2e9de4043e68)

![image](https://github.com/user-attachments/assets/019fe698-add2-443f-b062-611d1ec2dcf9)

![image](https://github.com/user-attachments/assets/6382cbd4-7915-4ba6-80d5-240e23240c3d)

![image](https://github.com/user-attachments/assets/a3823d35-54ba-4c2f-b129-3a5dc2b46d38)

![image](https://github.com/user-attachments/assets/a126afcf-6b9d-483d-955f-06694fcbcd85)

![image](https://github.com/user-attachments/assets/c8c0b598-30fe-4235-acd2-3d6517b54aff)

![image](https://github.com/user-attachments/assets/fe7242cb-f57e-4d23-8b2a-efc031685e24)

**System information**
 - Kali v2024.4
 - Python v3.12
 - Firefox

**Comment by snowpeacock** [comment]
Hello,
Are you using Bloodhound (or other tools) to compute paths during the AD Miner execution ?
Do you maybe have two AD Miner running in parallel ?

Could you try to stop everything else (especially Bloodhound GUI) and re-run AD Miner ?

**Comment by jmbesnard** [comment]
No. No need to reinstall Kali or whatever drastic measure. Can you reproduce the problem everytime you run AD-Miner (do not wait for it to finish). Especially on that very first query, because it really does not make sense. Also, to be 100% sure that there is no other process using the DB, just restart it before you re-run.

**Comment by jmbesnard** [comment]
Thanks for the feedback. Processing speed-up was introduced in the previous release already. 1.8.0 is mainly bug fixes.
