### ISSUE TITLE
no output in output folder

### ISSUE THREAD

**Issue by frankwiersma** [Mazars-Tech/AD_Miner#25]
After running it I end up with an empty html folder. 
The index.html is also non-functional.

Domain: TREE.DOMAIN.COM.PE

Error when all 119 checks are finished: 

Traceback (most recent call last):
  File "/home/pentest/.local/bin/AD-miner", line 8, in <module>
    sys.exit(main())
  File "/home/pentest/.local/pipx/venvs/ad-miner/lib/python3.10/site-packages/ad_miner/__main__.py", line 155, in main
    domains = Domains(arguments, neo4j)
  File "/home/pentest/.local/pipx/venvs/ad-miner/lib/python3.10/site-packages/ad_miner/sources/modules/domains.py", line 222, in __init__
    self.generatePathToOUHandlers(self)
  File "/home/pentest/.local/pipx/venvs/ad-miner/lib/python3.10/site-packages/ad_miner/sources/modules/domains.py", line 1582, in generatePathToOUHandlers
    self.paths_to_ou_handlers[path.nodes[-1].domain].append(path)
KeyError: 'TREE.DOMAIN.COM.PE'

**Comment by jmbesnard** [comment]
Hello. This a known bug that has been reported several times and is currently being fixed. We shall issue a fix today (or end of of week at the latest)

**Comment by jmbesnard** [comment]
Could you please run this and provide the output ?

MATCH (o) return o.domain,count(o) | cypher-shell -u neo4j -p password-a <IP>:<PORT>--format plain

**Comment by frankwiersma** [comment]
![neo4j](https://github.com/Mazars-Tech/AD_Miner/assets/15095308/86647b11-0de8-4c66-ba25-6e0f87ac13ad)
 Like this?

**Comment by jmbesnard** [comment]
OK, so apparently not the data quality issue that I was anticipating but just to be 100% sure could you modify the query like
MATCH (o) return labels(o),o.domain,count(o)

I just want to check that sole object that has no domain attribute is a Domain one.

If so, then I guess that we will need to add some debugging to troubleshoot this.

**Comment by frankwiersma** [comment]
Thanks for helping! 

Here you go!

![neo](https://github.com/Mazars-Tech/AD_Miner/assets/15095308/d252a9dd-aa84-4102-8512-49dd9e964a81)

**Comment by jmbesnard** [comment]
So, no "Domain" object ? It's probably easier if you come over to the Discord server to discuss this
