### ISSUE TITLE
Bump AD-miner version number in pyproject.toml upon release of new version

### ISSUE THREAD

**Issue by frankwiersma** [Mazars-Tech/AD_Miner#28]
Great work on this cool tool!

Can you bump AD-miner version numbers in pyproject.toml upon release of new versions?

**Comment by jmbesnard** [comment]
Thanks for reporting this. We have created. The next release shall ensure this gets updated automatically

**Comment by Tanguy-Boisset** [comment]
Previous fix #29 broke the pipx install so we need to find something else.

**Comment by Mazars-Tech** [comment]
Fixed in https://github.com/Mazars-Tech/AD_Miner/commit/21dfb09bf62fa779bda385f6befc59646ef406c7
