### ISSUE TITLE
TypeError - '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Th3FirstAvenger** [Mazars-Tech/AD_Miner#34]
**Describe the bug**
Upon executing the tool with default settings, I encountered a TypeError which prevented the correct generation of the /html/index.html file.
**Terminal Output**
```txt
Traceback (most recent call last):
  File "/home/capi/.local/bin/AD-miner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/capi/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/__main__.py", line 162, in main
    rating_dic = rating(users, domains, computers, objects, arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/capi/.local/pipx/venvs/ad-miner/lib/python3.11/site-packages/ad_miner/sources/modules/rating.py", line 165, in rating
    d[2 if users.number_group_ACL_anomaly > 0 else 5].append("group_anomaly_acl")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Screenshots**
![imagen](https://github.com/Mazars-Tech/AD_Miner/assets/67591596/1185787a-a408-4f4b-bf91-938bba0342af)

**System information**
 - OS Windows 11 and WSL kali
 - Python version Python 3.11.5

**Comment by thomas-girard** [comment]
Thank you for bringing this bug to our attention; it will be fixed in this PR: https://github.com/Mazars-Tech/AD_Miner/pull/36
